spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://shop-authorization-server:8081
          #jwk-set-uri: http://127.0.0.1:8081/oauth2/jwks


eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
    healthcheck:
      enabled: true
  instance:
    instanceId: ${random.uuid}
    prefer-ip-address: true